### ISSUE TITLE
Running tests inside a JAR dependency

### ISSUE THREAD

**Issue by andrelugomes** [opensanca/spring-arch-validation#4]
@juliofalbo I' m try to run arch tests from JAR using:

```
@RunWith(Suite.class)
@Suite.SuiteClasses({
        ResourceRulesTests.class
})
public class ArchTests {

}
```

`ResourceRulesTests.class` is from `arch-validator-1.0.0.jar`

Check this out demos folder

**Comment by lucasaquiles** [comment]
with dependence on the declared arch-validator-1.0.0.jar, would be a valid approach rather than running as a suite, run as one of the build phases of the type project, in the gradle verify for example?

**Comment by andrelugomes** [comment]
good idea.. let's talk more about.

**Comment by juliofalbo** [comment]
For the first version I think that we should create a custom Runner with possible to select which tests will be execute.

But I really like your idea @lucasaquiles, we can study this possiblity!

**Comment by juliofalbo** [comment]
I will commit this runner tonight!

**Comment by juliofalbo** [comment]
Please, take a look at the PR #5

**Comment by juliofalbo** [comment]
@andrelugomes, after our conversation, I changed the strategy!

```
@RunWith(ArqvRunner.class)
@ArqvRunner.RunTests(includingGroupRules = ArqvGroupRules.SPRING_REST_GROUPS_RULES,
        excludingRules = { ArqvRules.ALL_DELETE_MAPPING_SHOULD_RETURN_204,
                ArqvRules.ONLY_RESOURCES_MAY_USE_REST_CONTROLLER_ANNOTATION,
                ArqvRules.ALL_PATCH_MAPPING_SHOULD_RETURN_200 })
```

Take a look at the PR
